### ISSUE TITLE
Missing denominators?

### ISSUE THREAD

**Issue by mgkahn** [ncats/CTSA-Metrics#26]
These appear in document but not in spreadsheet
C2 denominator: Total # lab tests
D3 denominator: Total # medication records
E3 denominator: Total # diagnoses
F4 denominator: Total # unique diagnoses
G3 denominator: Total #procedures
G4 denominator: Total #unique procedures
L1 denominator: total # unique patients over age 12

For some of these (F3, F4, G3, G4 I3, I4), the numerators also are not in spreadsheet. Did I miss a version of the document that removed these?

**Comment by ams219** [comment]
I sent an email to you regarding these issues. I'm also attaching it here.

[Informatics 2.10.21.docx](https://github.com/ncats/CTSA-Metrics/files/6045250/Informatics.2.10.21.docx)
 Due to the issues collecting data and the need to finalize scripts the issues you mentioned (with the exception of L1) were excluded from collection.

**Comment by mgkahn** [comment]
Thanks. I was using 2/4/2021 version of the document and I missed the admonishment to ignore yellow highlighted measures. The highlighting gets lost in printing (I'm old so I print everything) so maybe use strikeout to keep the text in the document but more obvious that not to use. Thanks. Mark these as resolved.
